apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        ports:
        - containerPort: 9200
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          emptyDir: {}
